### ISSUE TITLE
Installing LINUX OS on Dell IDrac

### ISSUE THREAD

**Issue by Kuldeep-Admin** [dell/redfish-ansible-module#102]
Hi,

Hope you would be doing good.

We are looking for ansible scripts that could help us to deploy linux server using redfish API.

**Comment by anupamaloke** [comment]
@Kuldeep-Admin, you can use virtual media to attach an ISO image as a virtual CD and then do an one-time boot from virtual CD to deploy the OS. Please see the example playbook here https://github.com/dell/redfish-ansible-module/blob/master/playbooks/virtual_media/insert_virtual_media.yml

**Comment by anupamaloke** [comment]
@Kuldeep-Admin, as there has been no update since long, I am closing this issue. Please feel free to reopen or post a new issue for any follow-up questions.
