### ISSUE TITLE
Write scripts to parse through JSON data

### ISSUE THREAD

**Issue by jose-delarosa** [dell/redfish-ansible-module#35]
Extract data for easy import into a CSV file.

For example, a script could be called *extract_system_inventory_and_put_in_cvs_format.py*. When running this script, it would go and look at all the *xyz_YYYYMMDD_hhmmss_inventory.json* files, extract JSON data (using the jq or some other parser) and put all data in one master file, one row per server, with each entry separated by commas:

```bash
"PowerEdge R640",  "Physical", "Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz","Dell Inc.","1.0.7"..
```
The file should add a first row with column headers, so line above would become
```bash
"Model", "SystemType", "CpuModel", "Manufacturer", "BiosVersion",..
"PowerEdge R640",  "Physical", "Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz","Dell Inc.","1.0.7",..
```

**Comment by alansill** [comment]
You can combine raw jq output and the '@csv' filter to produce csv output. For example, to prepare a csv of manufacturer and model infomration from the get_system_inventory playbook, you could use:

> `echo '"Manufacturer","Model"'; jq -r '(.result | .entries[]) | [.Manufacturer, .Model] | @csv'  (playbook json output file)

to produce:

```
"Manufacturer","Model"
"Intel","Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz"
"Intel","Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz"
```

**Comment by alansill** [comment]
Here's a more general method that just reads the names of the columns from the playbook output and makes a CSV file from them witht he labels as given in the playbook output file:

`jq -r '.result'  (playbook json ooutput file) | jq -r '(.entries[0] | keys), (.entries[] | to_entries | map(.value)) | @csv'`

**Comment by alansill** [comment]
For sigle-layer results that don't have an entries layer, here's something that returns a CSV-formatted output. 

```
jq -r '(.result | keys), (.result | to_entries | map(.value)) | @csv' ../../output/compute-1-1/compute-1-1_SystemInventory_20180719_153558.json
```
returns
```
"AssetTag","BiosVersion","BootSourceOverrideMode","CpuCount","CpuHealth","CpuModel","HostName","Manufacturer","MemoryHealth","MemoryTotal","Model","PartNumber","PowerState","SerialNumber","ServiceTag","Status","SystemType","TPMInterfaceType","TPMStatus"
"","2.6.0","Not available",2,"OK","Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz","bright73.cm.cluster","Dell Inc.","OK",192,"PowerEdge C6320","082F9MA05","On","CN7475175G0154","2KTTHK2","OK","Physical","Not available","Not available"
```

**Comment by alansill** [comment]
Here's an example to parse through all of the node outputs of the NicInventory playbook and create a CSV of the results, adding the node name into each line of the CSV as appropriate. (Execute from the directory level just above the individual node output directories.)

> cat */*_NicInventory_*.json|jq -r '(.result | .entries[])|keys|@csv'|head -1|sed 's/^/\"Node\",/'>temp.csv
> while read f; do d=`echo $f | cut -f1 -d\/`; cat "$f"|jq -r '(.result | .entries[])|values|to_entries|map(.value)|@csv'|sed 's/^/'\"""$d""\",'/g'; done < <(find * -name *_NicInventory_*.json)>>temp.csv

This produces (obscuring the MAC addresses here):

> "Node","AutoNeg","FQDN","Health","MACAddress","MTU","Name","SpeedMbps","State"
> "compute-10-25",false,,"OK","AA:BB:CC:DD:00:11",,"System Ethernet Interface",10240,"Enabled"
> "compute-10-25",false,,"OK","AA:BB:CC:DD:00:11",,"System Ethernet Interface",0,"StandbyOffline"
> "compute-10-26",false,,"OK","AA:BB:CC:DD:00:11",,"System Ethernet Interface",10240,"Enabled"
> "compute-10-26",false,,"OK","AA:BB:CC:DD:00:11",,"System Ethernet Interface",0,"StandbyOffline"
> ...
