### ISSUE TITLE
Add options for VirtualMedia

### ISSUE THREAD

**Issue by jose-delarosa** [dell/redfish-ansible-module#39]
- Map
- Unmap
- Anything else?

**Comment by jose-delarosa** [comment]
Use /redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia

**Comment by jose-delarosa** [comment]
Look at implementing using SetAttributes command in idrac category.

**Comment by jcolby** [comment]
Great Work  Will it be possible to mount remote media (i.e. mount boot.iso via NFS)

**Comment by jose-delarosa** [comment]
Need to look if there is a Redfish API for it in iDRAC today, but yes this is definitely in the bucket list.

**Comment by jcolby** [comment]
> Need to look if there is a Redfish API for it in iDRAC today, but yes this is definitely in the bucket list

Looks like the only supported values in the current API are CD, DVD, and USBStick for both [13G](http://topics-cdn.dell.com/pdf/idrac7-8-lifecycle-controller-v2.40.40.40_API%20Guide_en-us.pdf) and [14G](http://topics-cdn.dell.com/pdf/idrac7-8-lifecycle-controller-v2.40.40.40_API%20Guide_en-us.pdf).

**Comment by jose-delarosa** [comment]
@jcolby can you tell me what those Redfish APIs are?

**Comment by jcolby** [comment]
@jose-delarosa The endpoint is /redfish/v1/Managers/<ID>/VirtualMedia for both 13G and 14G servers:

URL
/redfish/v1/Managers/<ID>/VirtualMedia
Supported HTTP methods and privileges
HTTP method Required privilege
GET Login
Supported status codes
HTTP status code Extended information
200
400
Redsh resources 53
HTTP status code Extended information
403 Insucient privileges.
500
Supported properties and values
Property Values
MediaTypes
• CD
• DVD
• USBStick
ConnectedVia
• NotConnected
• Apple
