### ISSUE TITLE
Firmware upgrade failing

### ISSUE THREAD

**Issue by jose-delarosa** [dell/redfish-ansible-module#53]
Getting error code 400 in schedule_firmware_update(), opening bug for tracking purposes.

**Comment by jose-delarosa** [comment]
Tracking in fordell branch.

**Comment by jose-delarosa** [comment]
Looks like it can only do one FW upgrade at a time per POST call, so create a loop to pass each DUP individually (with Now option) in fw[] and then the last one can be done with NowAndReboot.

**Comment by virtualluke** [comment]
Does the firmware_update work with a 13G R730xd running 2.50.50.50 (idrac8)?

**Comment by jose-delarosa** [comment]
@virtualluke, firmware updates are currently only available in 14G (iDRAC9) servers.

**Comment by mrala** [comment]
@jose-delarosa, it would be useful to have that information in the README.

**Comment by aerove26** [comment]
Hi Jose, any updates on this bug ? i am using a 14G R640. I started seeing this issue this week. Earlier the update was working if i didn't hit my previous issue.

**Comment by jose-delarosa** [comment]
@aerove26 No updates, have not had time to work on it. But, just to be 100% clear, have you been using these Ansible modules ([fordell](https://github.com/dell/redfish-ansible-module/tree/fordell) branch) or the  scripts in this repo:  https://github.com/dell/iDRAC-Redfish-Scripting? Although the FW update method is very similar (same APIs being used), they are different implementations with different maintainers.

I also asked in https://github.com/dell/redfish-ansible-module/issues/69 that you opened, want to make sure you're asking in the right place.
