### ISSUE TITLE
SSL Protocol error

### ISSUE THREAD

**Issue by jose-delarosa** [dell/redfish-ansible-module#63]
After moving from requests library to ansible.module_utils.urls.open_url, I see some sporadic errors:

``
URL Error: EOF occurred in violation of protocol (_ssl.c:579)
``

Errors are intermittent, and possibly caused by TLS certificates in OOB controller. (?)

**Comment by patriziobassi** [comment]
some for me, just need to retry. It looks like a sort of timeout, previously i tought it was self signed cert issue

**Comment by jose-delarosa** [comment]
Appears to happen more often in 13G and 12G servers, not so much in 14G. Still no closer to resolution.

**Comment by ChristopheWuzHere** [comment]
I'm using RHEL 7.5 and seeing this issue, curious if there's any variation to this problem across distros....?

**Comment by jose-delarosa** [comment]
Only variation that I've seen is that it happens more often in 12G and 13G servers, and in fact I don't think I've seen it in 14G servers, though that is a good point, I mostly test on RHEL 7, would be interesting to test with other distros (I will add that to my to-do list).

Could be the way the self-signed SSL certificates are implemented in 12/13G vs. 14G, though just a theory. It is frustrating because the error message in intermittent, not constant.

I would go back to the requests() library but upstream prefers using the built-in open_url() function.

**Comment by ChristopheWuzHere** [comment]
Would it be difficult to allow users to select requests() library OR open_url() when executing the playbook?  I.e. via parameter, variable, etc...

**Comment by jose-delarosa** [comment]
Upgrading to latest iDRAC FW on 12G/13G/14G helps a lot. I can't see errors anymore. I don't know what changed in latest FW versions that stopped the SSL errors (wish I had the time to read the update logs). Leaving open for now until I get confirmation from others.

**Comment by alansill** [comment]
I still see the issue in 2.50.50 for 13G servers.

**Comment by jose-delarosa** [comment]
Latest for 13G is 2.60.60.60, that's what I'm using.

**Comment by jose-delarosa** [comment]
Going to close this issue, have not it on 12G/13G/14G with **latest iDRAC Firmware**. If you see it again, please reopen and provide specific details on server and iDRAC FW level.
