### ISSUE TITLE
Output color/PLAY RECAP not indicating if task changed anything (yellow vs green)

### ISSUE THREAD

**Issue by goetzrieger** [dell/redfish-ansible-module#65]
Just put together a simple demo (add user, configure NTP/timezone, get inventory on some Dell R740) and noticed that Ansible's output is not reflecting if a task actually changed (aka "Yellow") anything but is always "Green".

Is this something the Redfish API is not providing?

**Comment by RBakkum** [comment]
Very much would like to see when settings are changed instead of always see it 'as' ok but still changing settings.

**Comment by jose-delarosa** [comment]
Valid request. I will have to look at it at a later time. Keep in mind that all Ansible connections are local (we don't communicate with hosts via ssh, but build Redfish URIs dynamically and then send to iDRAC) so some returned information/status has to be captured differently.

**Comment by jose-delarosa** [comment]
Tracked in https://github.com/ansible/ansible/issues/46338, so will close this one.
