### ISSUE TITLE
Firmware update fails with status code 413 ..  error code : 400 

### ISSUE THREAD

**Issue by aerove26** [dell/redfish-ansible-module#69]
It failed when i ran the upgrade_firmware.yml , is there some configuration that i'm supposed to do? 

failed: [testhost -> localhost] (item={u'path': u'FOLDER04936438M/1/Drivers-for-OS-Deployment_Application_RHM02_WN64_18.04.07_A00.EXE', u'curr': u'17.08.12', u'latest': u'18.04.07'}) => {"changed": false, "item": {"curr": "17.08.12", "latest": "18.04.07", "path": "FOLDER04936438M/1/Drivers-for-OS-Deployment_Application_RHM02_WN64_18.04.07_A00.EXE"}, "msg": "Error uploading firmware; status_code=413"}

.
.
.
.
TASK [install firmware image] *******************************************************************************************************************************************************************************************************************
fatal: [testhost -> localhost]: FAILED! => {"changed": false, "msg": "Error code 400"}

**Comment by jose-delarosa** [comment]
Yup, already aware: https://github.com/dell/redfish-ansible-module/issues/53. I have been focusing on other areas of this project and have not focused on this feature, but will eventually get to it. Unless I'm missing something, I'll close this as a dup.

**Comment by aerove26** [comment]
Hi Jose,

It happens even when i just use the python script to do the firmware update. So might not be a bug in the ansible script itself?

with the python script..

- WARNING, downloading "Drivers-for-OS-Deployment_Application_RHM02_WN64_18.04.07_A00.EXE" image payload to iDRAC

- FAIL: POST command failed to download image payload, error is <Response [413]>

More details on status code error: {"error":{"@Message.ExtendedInfo":[{"Message":"Unable to upload the file because the file size is greater than specified limit.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.1.6.SYS411","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Make sure that the file size is less than the specified limit. For information about specified limit, see the Redfish User's Guide available on the support site.","Severity":"Warning"}],"code":"Base.1.0.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information"}}

**Comment by jose-delarosa** [comment]
Which python script are you referring to? From [here](https://github.com/dell/iDRAC-Redfish-Scripting/tree/master/Redfish%20Python)?

**Comment by aerove26** [comment]
Yep that one.

**Comment by jose-delarosa** [comment]
@aerove26, please open an issue in https://github.com/dell/iDRAC-Redfish-Scripting/issues and close this once since it applies to that repository.
