### ISSUE TITLE
Playbooks do not work in latest version of ansible (2.6.1 in this case)

### ISSUE THREAD

**Issue by alansill** [dell/redfish-ansible-module#71]
When running any of the playbooks using the currently most recent version available of ansible, I get errors like

> ansible-playbook get_cpu_inventory.yml
> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
> 
> The error appears to have been in '/root/dell/redfish-ansible/fordell/redfish-ansible-module/playbooks/get_cpu_inventory.yml': line 15, column 5, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
>   - name: Get CPU Inventory
>     ^ here

I have updated to the latest versions of python, including setuptoools and pip, and of ansible available:

ansible-playbook --version
ansible-playbook 2.6.1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/ansible
  executable location = /opt/rh/rh-python35/root/usr/bin/ansible-playbook
  python version = 3.5.1 (default, Oct 21 2016, 21:37:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

The resolution appears to be to specify an additional path to include the module_utils area when issuing the ansible-playbook command. In my case, I was using the "Softwre Collections" version of Python to get to the currently required version 3.5 or greater of Python for the current version of Ansible to run, so the path is:

ansible-playbook --module-path=/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/ansible/module_utils playbooks/get_cpu_inventory.yml

In general, the path to add will probably be the third one listed when the "python install.py" command runs.

**Comment by jose-delarosa** [comment]
Thank you for reporting Dr. Sill. Please note that development has moved to https://github.com/ansible/ansible, starting with Ansible v2.7, so this issue should not be there.
