### ISSUE TITLE
jq examples probably need to be updated

### ISSUE THREAD

**Issue by alansill** [dell/redfish-ansible-module#73]
I am entering this as an issue rather than as a pull request because this might depend on details of the setup I am using.

If I enter the jq example as given in the current README for the results of the CPU inventory playbook, or presumably any playbook that returns an extra layer (in this case "entries") in its json output, 

> jq '.result | {Manufacturer: .Manufacturer, Name: .Model}' (json file from playbook output)

I get null results. 

```
{
  "Manufacturer": null,
  "Name": null
}

```

This is apparently due to an extra "entries" layer in the json output, which looks like this raw:

```
{
  "changed": false,
  "failed": false,
  "result": {
    "entries": [
      {
        "Health": "OK",
        "Manufacturer": "Intel",
        "MaxSpeedMHz": 4000,
        "Model": "Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz",
        "Name": "CPU.Socket.1",
        "State": "Enabled",
        "TotalCores": 18,
        "TotalThreads": 36
      },
      {
        "Health": "OK",
        "Manufacturer": "Intel",
        "MaxSpeedMHz": 4000,
        "Model": "Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz",
        "Name": "CPU.Socket.2",
        "State": "Enabled",
        "TotalCores": 18,
        "TotalThreads": 36
      }
    ]
  }
}

```

If I instead change the jq parsing string to accommodate the extra "entries" layer, it works, e.g.:

> jq '(.result | .entries[]) | {Manufacturer: .Manufacturer, Name: .Model}'  (json file from playbook output)

produces:

```
{
  "Manufacturer": "Intel",
  "Name": "Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz"
}
{
  "Manufacturer": "Intel",
  "Name": "Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz"
}

```

**Comment by jose-delarosa** [comment]
@alansill Thanks for reporting, I have been focused lately on pushing this code upstream but do need to update code and documentation here. Will take a look at all your reported issues, thank you for your feedback.

**Comment by jose-delarosa** [comment]
Please note, I've made some updates (patches that I will merge this weekend hopefully) to the format of the output files. I still have an "entries" list though. Tried to come up with the best generic organization given there are different types of information that can be retrieved. For a lot of items, a list is necessary: list of CPUs, list of fans, list of HDD, etc. In other cases, (like FW inventory), 'entries' is a dict.

Do you consider this a bug because the documentation doesn't reflect it?

**Comment by jose-delarosa** [comment]
Closing here, will track upstream.
