### ISSUE TITLE
Module failures during playbook runs

### ISSUE THREAD

**Issue by aarongreen85** [dell/redfish-ansible-module#77]
When trying to run the get_system_inventory playbook, I'm getting the following -

"module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_agtZY8/ansible_module_redfish.py\", line 367, in <module>\n    main()\n  File \"/tmp/ansible_agtZY8/ansible_module_redfish.py\", line 224, in main\n    result = rf_utils._find_systems_resource(rf_uri)\n  File \"/tmp/ansible_agtZY8/ansible_modlib.zip/ansible/module_utils/redfish_utils.py\", line 104, in _find_systems_resource\n  File \"/tmp/ansible_agtZY8/ansible_modlib.zip/ansible/module_utils/redfish_utils.py\", line 48, in send_get_request\nTypeError: get() takes exactly 1 argument (4 given)\n", "module_stdout": "", "msg": "MODULE FAILURE"

My package versions are -

ansible-2.4.2.0-2.el7.noarch
python-requests-2.6.0-1.el7_1.noarch
python-urllib3-1.10.2-5.el7.noarch

**Comment by jose-delarosa** [comment]
Please refer to https://github.com/dell/redfish-ansible-module/issues/68

**Comment by aarongreen85** [comment]
Issue #68 helped me get past that first error, sorry for not seeing that prior.

I am now seeing the following. Is this related to #63?

"module_stderr": "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_YnP7Od/ansible_module_redfish.py\", line 367, in <module>\n    main()\n  File \"/tmp/ansible_YnP7Od/ansible_module_redfish.py\", line 224, in main\n    result = rf_utils._find_systems_resource(rf_uri)\n  File \"/tmp/ansible_YnP7Od/ansible_modlib.zip/ansible/module_utils/redfish_utils.py\", line 105, in _find_systems_resource\n  File \"/usr/lib/python2.7/site-packages/requests/models.py\", line 896, in json\n    return complexjson.loads(self.text, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/simplejson/__init__.py\", line 518, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib64/python2.7/site-packages/simplejson/decoder.py\", line 370, in decode\n    obj, end = self.raw_decode(s)\n  File \"/usr/lib64/python2.7/site-packages/simplejson/decoder.py\", line 400, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\nsimplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "module_stdout": "", "msg": "MODULE FAILURE",

**Comment by jose-delarosa** [comment]
Is this using the master branch? What server(s) are you using? have not seen this in a while. Not directly related to https://github.com/dell/redfish-ansible-module/issues/63, I don't think.

**Comment by aarongreen85** [comment]
Sorry for the lack of update as I've been away with business and personal travel and am now back to trying to get this functionality to work again. I was using a CentOS box in the latest update, but decided to stop trying on CentOS as that doesn't fall in line with our long term plans for this. I am now running this from a RHEL 7.5 server. I'm using pip based on this link https://access.redhat.com/solutions/1519803.

If I'm running the playbooks in a bash session with scl enabled (scl enable python27 bash), then I get the following errors -

TASK [Getting system inventory] ***************************************************************************************************************************************************
fatal: [node03]: FAILED! => {"msg": "The module redfish was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git pull --rebase' to correct this problem."}

If I run without scl enabled, I revert back to the failures I got at the beginning of opening this issue.

Thanks for the replies so far. Hoping to be able to use this in the very near future.

**Comment by aarongreen85** [comment]
I was able to fix this issue. Red Hat's software collections is a virtual environment. Once in it, reran the install.py script which resolved the above issue. Had another issue with libselinux-python but fixed it by soft linking from the installed location to the virtual environment location for those python modules. If more detail is desired, let me know and I'll post it here. Again, thanks for the help. Looking forward to using these ansible modules.

**Comment by jose-delarosa** [comment]
Glad your issue is solved. As a reminder (and as stated in the README.md), development of this module has moved to https://github.com/ansible/ansible:

- https://docs.ansible.com/ansible/devel/modules/redfish_facts_module
- https://docs.ansible.com/ansible/devel/modules/redfish_command_module
- https://docs.ansible.com/ansible/devel/modules/redfish_config_module
