### ISSUE TITLE
ansible-playbook 2.7.10 | Module not found

### ISSUE THREAD

**Issue by aishkings** [dell/redfish-ansible-module#90]
fatal: [localhost]: FAILED! => {
    "msg": "The module vmware_tag_manager was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git pull --rebase' to correct this problem."
}
          module: vmware_tag_manager
Please can anyone advise on this..

**Comment by jose-delarosa** [comment]
Wrong repo. Although I do see that module in the Ansible repository.

`lib/ansible/modules/cloud/vmware/vmware_tag_manager.py`
